SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:noga2110@localhost/dotbot_db"
SQLALCHEMY_COMMIT_ON_TEARDOWN = 'True'
SQLALCHEMY_ECHO=False
SQLALCHEMY_TRACK_MODIFICATIONS=True

SECURITY_RECOVERABLE    = True
SECURITY_SEND_CONFIRMATION_TEMPLATE = 'security/others.html'